code4lib/2019.code4lib.org

assets/_scss/_color-contrast.scss
assets/_scss/_variables.scss
assets/css/main.scss

new color scheme

---

_includes/homepage/pre_conference.html

shows up on home page & schedule section now

hotel info in preconf display

---

assets/_scss/_sponsors.scss

Fix text color for prospectus page. Closes #16 .

prospectus text color

---

README.md

Jekyll has no relationship to Rails.

Change Rails -> Ruby

---

assets/_scss/_variables.scss
assets/css/main.scss

This is only covering the color contrast issues and not other accessibility ones  ✌️

Color contrast is insufficient fixes

---

_includes/header.html

Fixes the link to the apple touch icon across the site.

Resolves the 'apple-touch-icon' issue

---

_data/past-keynotes.yml

Change link text for Chris Bourg and Mega Subramaniam's detailed bios

---

conduct/index.html
general-info/accessibility.html

Hide nav items that don't have content yet.

---

_data/testimonials.yml

includes all, regardless of size for checking out what looks alright and what's too much. also included both of Becky's so voting to do here.

Initial Round of Updated Testimonials for 2k19 

---

_data/testimonials.yml

took out Becky's funny quote

---

_includes/homepage/jumbotron.html
assets/css/main.scss

also added tentative font weight bold, if needed, on the css file. it's commented out for now.

image attribution text: increase font size

---

_includes/homepage/pre_conference.html
_includes/nav.html
assets/css/main.scss

small edits to get accessibility audits back on track 
ref: https://github.com/code4lib/2019.code4lib.org/issues/18

dont use b tags, use aria-labels and some text-underlines

---

_data/conf.yml
assets/_scss/_sponsors.scss
prospectus/index.html

also adds the contact email for Sponsorship and LPC (not used anywhere yet)

Sponsorship - prospectus updates

---

_data/conf.yml

Open call for proposals

---

.gitignore
_data/testimonials.yml

Sonoe got back to me on their Org and Twitter username

adding org and twitter for a testimonial

---

_includes/homepage/pre_conference.html

The conference hotel is kind of old news now, I think it makes more sense for the open proposals to be on top.

push proposals section up above conf hotel

---

_data/conf.yml
general-info/propose-a-workshop.html

Add call for pre-conference proposals

---

_data/conf.yml
_includes/homepage/pre_conference.html
general-info/propose-a-keynote.html

open keynote proposals and add extra info page

---

_data/conf.yml

close talk CFP

---

_data/conf.yml
_data/presentation-proposals.yml

Opens voting for talks and adds proposals. Closes #66.

Open talk voting

---

assets/css/main.scss

No longer will buttons on hover state be unreadable

fixing button hover

---

prospectus/index.html

Reverts code4lib/2019.code4lib.org#75

Revert "we have one childcare sponsor, update prospectus"

---

prospectus/index.html

update num childcare sponsors

---

_data/conf.yml

close keynote proposals

---

general-info/angel-fund.html
general-info/scholarships.html

Fix so assets load on https://2019.code4lib.org/general-info/angel-fund.html

change link to angel fund

---

_data/conf.yml
_includes/homepage/jumbotron.html
general-info/propose-a-keynote.html
general-info/scholarships.html
index.html

Takes care of small part of #64 and closes #87.

Open scholarship applications and improve some conf variables

---

_data/conf.yml
_includes/homepage/pre_conference.html

Open poster session proposals

---

_data/conf.yml
_includes/homepage/pre_conference.html
assets/css/main.scss

Add a volunteer section to the landing/schedule pages for committees and duty officers; lighten the underline colour for headings. Closes #83.

Issue # 83 - volunteer section

---

_includes/workshops/card.html
_layouts/presentation.html
_posts/2019-02-19-Accessible-Websites-Made-Easy-How-To-Assess-Issues-and-Create-Better-Experiences.html
_posts/2019-02-19-Advocating-for-Library-Accessibility-An-Introduction.html
_posts/2019-02-19-All-the-Things-NiFi-for-Data-Processing-API-requests-and-More.html
_posts/2019-02-19-ArchivesSpace-in-a-Day-Installing-and-Customizing-AS-in-the-Cloud.html
_posts/2019-02-19-Fail4Lib-2019.html
_posts/2019-02-19-ISLE-Islandora-for-All.html
_posts/2019-02-19-Introduction-to-Handling-Data-and-SQL.html
_posts/2019-02-19-LD4Ps-Sinopia-Linked-Data-Editing-Environment.html
_posts/2019-02-19-Leveraging-Serverless-Technologies-to-Improve-Library-Workflows.html
_posts/2019-02-19-Practicing-ethics-in-information-professions.html
_posts/2019-02-19-Using-Node-to-Listen-to-Alma-Webhooks.html
_posts/2019-02-19-Wait-what-Getting-your-bearings-with-ServerSpec.html

fix #100 - better handling of workshop start & end times

---

_data/examples/speakers.yml
_data/speakers.yml
_includes/presentation_timeline.html
_includes/presentation_timeline_past.html
_includes/speaker_box.html
_layouts/presentation.html

- update data keys work-title -> work_title etc. to match templates
- where we were using `{{ speaker.image_src }}` we should be filtering through `relative_url`

underscores in data keys, relative URLs for speaker img

---

assets/_scss/_color-contrast.scss
assets/_scss/_variables.scss
assets/css/main.scss

Still some lingering contrast issues, but those can be addressed separately. Closes #114.

Fix background colour for speaker boxes, plus minor formatting cleanup

---

_data/conf.yml

close poster voting

---

_data/conf.yml
schedule/index.html

rather than hard-coded dates, ref #64

use conf.yml for conference days

---

_data/conf.yml
_posts/2019-02-20-Aggregation-Without-Aggravation-auditing-metadata-at-scale.md
_posts/2019-02-20-Algorithm-Bias-Study.md
_posts/2019-02-20-Automating-link-management-When-institutional-infrastructure-works-against-you.md
_posts/2019-02-20-Blockchain-for-Libraries-is-Snake-Oil.md
_posts/2019-02-20-Building-A-Better-Database-List-with-APIs.md
_posts/2019-02-20-Building-REST-APIbacked-Single-Page-Applications-SPAs-with-Vuejs.md
_posts/2019-02-20-Code-It-Yourself-Teaching-Collections-Staff-to-Script.md
_posts/2019-02-20-Consortial-discovery-and-resource-sharing-making-it-happen-with-mostly-standard-tools.md
_posts/2019-02-20-Enrich-Library-Collection-Analysis-using-Python.md
_posts/2019-02-20-Ethics-for-information-professionals.md
_posts/2019-02-20-GDPR-for-American-Public-Libraries.md
_posts/2019-02-20-Get-To-Know-WCAG-21.md
_posts/2019-02-20-Looking-for-Some-Hot-Stuff-Collaborating-on-the-Disco-Index-Project.md
_posts/2019-02-20-Machine-Learning-and-Metadata-with-the-Charles-Teenie-Harris-Archive.md
_posts/2019-02-20-Machine-Learning-based-metadata-generation-for-library-archives.md
_posts/2019-02-20-Natural-Language-Processing-for-Discovery-of-BornDigital-Records.md
_posts/2019-02-20-Of-Ethics-Users-and-Data-Building-a-National-Conversation-for-Web-Privacy-and-Web-Analytics.md
_posts/2019-02-20-Optimizing-Library-Web-Content-for-Voice-Search.md
_posts/2019-02-20-Programmatic-approaches-to-bias-in-descriptive-metadata.md
_posts/2019-02-20-Project-ReShare-Development--Piloting-of-an-Open-Source-Resource-Sharing-Platform.md
_posts/2019-02-20-Providing-Computational-Access-to-Records-of-American-Capital-Punishment.md
_posts/2019-02-20-Ringers-of-Jupyter-The-Jupyter-Notebook-As-Faux-Web-App.md
_posts/2019-02-20-Shear-forces-a-conceptual-model-for-understanding-and-coping-with-risk-change-and-technical-debt.md
_posts/2019-02-20-The-Websites-that-Librarians-Love-but-are-they-ACCESSIBLE.md
_posts/2019-02-20-Using-MediaWiki--WikiBase-as-a-platform-for-library-linked-data-a-pilot-study.md
_posts/2019-02-20-Webrecorder-Developing-an-OpenSource-HighFidelity-Web-Archiving-Toolset.md
_posts/2019-02-20-Why-building-a-complete-index-of-open-access-to-research-articles-is-hard-and-how-you-can-help.md

add group numbers to talks, activate program nav links

---

_data/conf.yml
_data/schedule.yml
_posts/keynotes/2019-02-20-Tara-Robertson.html
_posts/keynotes/2019-02-22-Safiya-Noble.html
general-info/venues/dinner.html
general-info/venues/index.html
schedule/index.html

- posts for keynotes so the links on schedule work
- hide all menus on the schedule
- hide newcomer dinner details from last year
- hide game night & reception
- add basic conf.yml configuration for all the above events (dinner, game night, reception)

several schedule details

---

_data/conf.yml
general-info/accessibility.html
general-info/first-timers.html
general-info/venues/dinner.html
general-info/venues/reception.html

I'm going to try and make a links.yml file for the other vars involving external social media links

variables for accessibility email/reception& newcomer dinner dates

---

_posts/2019-02-19-Forensic-Files-Episode-1-Fishing-for-the-Truth.md

add Ashley Blewer to Forensic Files 1 preconf

---

_data/conf.yml
general-info/accessibility.html
general-info/first-timers.html

add quiet room info, add conf variables, minor text cleanup

---

_layouts/presentation.html
assets/css/main.scss

adding a small nav item to easily go back to full workshop list

---

_data/schedule.yml
general-info/venues/reception.html
schedule/index.html

reception is 6:30-8:30 this near not 7-9
there will be a breakfast served 8-9am during main conf days

couple schedule updates, breakfast & reception time

---

_data/conf.yml
_includes/homepage/pre_conference.html

also turn off committee volunteers

onsite volunteer link on home pg

---

_data/conf.yml

add conf slide repository, closes #182

---

sponsors/index.html

Current code commented out (just in case!) , new logic added in above

logic for empty categories

---

schedule/index.html

fix newcomer dinner link

---

general-info/first-timers.html
general-info/venues/gaming.html

fix date for game night, add to first timers guide

update game night date and add to first timers guide

---

_data/day1-menus.yml
_data/day2-menus.yml
_data/day3-menus.yml
_data/schedule.yml

add menu info and show on the schedule page

---

_data/day1-menus.yml
_data/day2-menus.yml
_data/day3-menus.yml
_data/schedule.yml
_includes/menu.html
schedule/index.html

adding what we've gotten for the hotel/reception. Wasn't sure if we should add allergen info for beverages, but I can do that too if we want.

menu and allergen updates
